# Generated by Django 4.2.3 on 2023-10-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/placeholder.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
