# Generated by Django 4.2.3 on 2023-09-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_city_shippingaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
